name: Continuous integration workflow
on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Node.js 10.x
        uses: actions/setup-node@master
        with:
          node-version: 10.x
      - name: Install
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test library
        run: npm run test:library:ci
      - name: Test application
        run: npm run test:app:ci
      - name: Run e2e tests
        run: npm run e2e:ci
